### ISSUE TITLE
add config/bookinfo.yml file for book settings and information

### ISSUE THREAD

**Issue by blueheadpublishing** [worlduniting/old-bookshop#2]
user should be able to edit the config/bookinfo.yml file with information about the book that is not otherwise contained in the book content.

these settings should be added in yaml so they can become available as an object to the bookshop library.

```
# config/bookinfo.yml
book:
  title: This is the Title
  subtitle: This is the Subtitle
  isbn: 1234567891011 # isbn-13
  author: Author Name
  publisher: Publisher Name
  contributor_1: Contributor Name

  # EPUB specific settings
  epub:
    contributor_1: Contributor Name For Epub
```
